/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResetPasswordTokenRouteImport } from './routes/reset-password.$token'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalSecurityRouteImport } from './routes/legal.security'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSitesIdRouteImport } from './routes/_authenticated/sites.$id'
import { Route as AuthenticatedSettingsTeamRouteImport } from './routes/_authenticated/settings.team'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated/settings.integrations'
import { Route as AuthenticatedSettingsGeneralRouteImport } from './routes/_authenticated/settings.general'
import { Route as AuthenticatedSettingsActivityRouteImport } from './routes/_authenticated/settings.activity'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects.new'
import { Route as AuthenticatedProjectsIdSitesRouteImport } from './routes/_authenticated/projects.$id.sites'
import { Route as AuthenticatedProjectsIdIssuesRouteImport } from './routes/_authenticated/projects.$id.issues'
import { Route as AuthenticatedProjectsIdExportsRouteImport } from './routes/_authenticated/projects.$id.exports'
import { Route as AuthenticatedProjectsIdAuditsRouteImport } from './routes/_authenticated/projects.$id.audits'
import { Route as AuthenticatedSitesIdAuditsAuditIdRouteImport } from './routes/_authenticated/sites_.$id.audits.$auditId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordTokenRoute = ResetPasswordTokenRouteImport.update({
  id: '/reset-password/$token',
  path: '/reset-password/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSecurityRoute = LegalSecurityRouteImport.update({
  id: '/legal/security',
  path: '/legal/security',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSitesIdRoute = AuthenticatedSitesIdRouteImport.update({
  id: '/sites/$id',
  path: '/sites/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsTeamRoute =
  AuthenticatedSettingsTeamRouteImport.update({
    id: '/settings/team',
    path: '/settings/team',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsGeneralRoute =
  AuthenticatedSettingsGeneralRouteImport.update({
    id: '/settings/general',
    path: '/settings/general',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsActivityRoute =
  AuthenticatedSettingsActivityRouteImport.update({
    id: '/settings/activity',
    path: '/settings/activity',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIdSitesRoute =
  AuthenticatedProjectsIdSitesRouteImport.update({
    id: '/projects/$id/sites',
    path: '/projects/$id/sites',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIdIssuesRoute =
  AuthenticatedProjectsIdIssuesRouteImport.update({
    id: '/projects/$id/issues',
    path: '/projects/$id/issues',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIdExportsRoute =
  AuthenticatedProjectsIdExportsRouteImport.update({
    id: '/projects/$id/exports',
    path: '/projects/$id/exports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIdAuditsRoute =
  AuthenticatedProjectsIdAuditsRouteImport.update({
    id: '/projects/$id/audits',
    path: '/projects/$id/audits',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSitesIdAuditsAuditIdRoute =
  AuthenticatedSitesIdAuditsAuditIdRouteImport.update({
    id: '/sites_/$id/audits/$auditId',
    path: '/sites/$id/audits/$auditId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/security': typeof LegalSecurityRoute
  '/legal/terms': typeof LegalTermsRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/settings/activity': typeof AuthenticatedSettingsActivityRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/sites/$id': typeof AuthenticatedSitesIdRoute
  '/projects/$id/audits': typeof AuthenticatedProjectsIdAuditsRoute
  '/projects/$id/exports': typeof AuthenticatedProjectsIdExportsRoute
  '/projects/$id/issues': typeof AuthenticatedProjectsIdIssuesRoute
  '/projects/$id/sites': typeof AuthenticatedProjectsIdSitesRoute
  '/sites/$id/audits/$auditId': typeof AuthenticatedSitesIdAuditsAuditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/security': typeof LegalSecurityRoute
  '/legal/terms': typeof LegalTermsRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/settings/activity': typeof AuthenticatedSettingsActivityRoute
  '/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/sites/$id': typeof AuthenticatedSitesIdRoute
  '/projects/$id/audits': typeof AuthenticatedProjectsIdAuditsRoute
  '/projects/$id/exports': typeof AuthenticatedProjectsIdExportsRoute
  '/projects/$id/issues': typeof AuthenticatedProjectsIdIssuesRoute
  '/projects/$id/sites': typeof AuthenticatedProjectsIdSitesRoute
  '/sites/$id/audits/$auditId': typeof AuthenticatedSitesIdAuditsAuditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/security': typeof LegalSecurityRoute
  '/legal/terms': typeof LegalTermsRoute
  '/reset-password/$token': typeof ResetPasswordTokenRoute
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/settings/activity': typeof AuthenticatedSettingsActivityRoute
  '/_authenticated/settings/general': typeof AuthenticatedSettingsGeneralRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/settings/team': typeof AuthenticatedSettingsTeamRoute
  '/_authenticated/sites/$id': typeof AuthenticatedSitesIdRoute
  '/_authenticated/projects/$id/audits': typeof AuthenticatedProjectsIdAuditsRoute
  '/_authenticated/projects/$id/exports': typeof AuthenticatedProjectsIdExportsRoute
  '/_authenticated/projects/$id/issues': typeof AuthenticatedProjectsIdIssuesRoute
  '/_authenticated/projects/$id/sites': typeof AuthenticatedProjectsIdSitesRoute
  '/_authenticated/sites_/$id/audits/$auditId': typeof AuthenticatedSitesIdAuditsAuditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/notifications'
    | '/invite/$token'
    | '/legal/privacy'
    | '/legal/security'
    | '/legal/terms'
    | '/reset-password/$token'
    | '/projects/new'
    | '/settings/activity'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/team'
    | '/sites/$id'
    | '/projects/$id/audits'
    | '/projects/$id/exports'
    | '/projects/$id/issues'
    | '/projects/$id/sites'
    | '/sites/$id/audits/$auditId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/notifications'
    | '/invite/$token'
    | '/legal/privacy'
    | '/legal/security'
    | '/legal/terms'
    | '/reset-password/$token'
    | '/projects/new'
    | '/settings/activity'
    | '/settings/general'
    | '/settings/integrations'
    | '/settings/team'
    | '/sites/$id'
    | '/projects/$id/audits'
    | '/projects/$id/exports'
    | '/projects/$id/issues'
    | '/projects/$id/sites'
    | '/sites/$id/audits/$auditId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/invite/$token'
    | '/legal/privacy'
    | '/legal/security'
    | '/legal/terms'
    | '/reset-password/$token'
    | '/_authenticated/projects/new'
    | '/_authenticated/settings/activity'
    | '/_authenticated/settings/general'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/settings/team'
    | '/_authenticated/sites/$id'
    | '/_authenticated/projects/$id/audits'
    | '/_authenticated/projects/$id/exports'
    | '/_authenticated/projects/$id/issues'
    | '/_authenticated/projects/$id/sites'
    | '/_authenticated/sites_/$id/audits/$auditId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  InviteTokenRoute: typeof InviteTokenRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalSecurityRoute: typeof LegalSecurityRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ResetPasswordTokenRoute: typeof ResetPasswordTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/$token': {
      id: '/reset-password/$token'
      path: '/reset-password/$token'
      fullPath: '/reset-password/$token'
      preLoaderRoute: typeof ResetPasswordTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/security': {
      id: '/legal/security'
      path: '/legal/security'
      fullPath: '/legal/security'
      preLoaderRoute: typeof LegalSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sites/$id': {
      id: '/_authenticated/sites/$id'
      path: '/sites/$id'
      fullPath: '/sites/$id'
      preLoaderRoute: typeof AuthenticatedSitesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/team': {
      id: '/_authenticated/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AuthenticatedSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/general': {
      id: '/_authenticated/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AuthenticatedSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/activity': {
      id: '/_authenticated/settings/activity'
      path: '/settings/activity'
      fullPath: '/settings/activity'
      preLoaderRoute: typeof AuthenticatedSettingsActivityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$id/sites': {
      id: '/_authenticated/projects/$id/sites'
      path: '/projects/$id/sites'
      fullPath: '/projects/$id/sites'
      preLoaderRoute: typeof AuthenticatedProjectsIdSitesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$id/issues': {
      id: '/_authenticated/projects/$id/issues'
      path: '/projects/$id/issues'
      fullPath: '/projects/$id/issues'
      preLoaderRoute: typeof AuthenticatedProjectsIdIssuesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$id/exports': {
      id: '/_authenticated/projects/$id/exports'
      path: '/projects/$id/exports'
      fullPath: '/projects/$id/exports'
      preLoaderRoute: typeof AuthenticatedProjectsIdExportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$id/audits': {
      id: '/_authenticated/projects/$id/audits'
      path: '/projects/$id/audits'
      fullPath: '/projects/$id/audits'
      preLoaderRoute: typeof AuthenticatedProjectsIdAuditsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sites_/$id/audits/$auditId': {
      id: '/_authenticated/sites_/$id/audits/$auditId'
      path: '/sites/$id/audits/$auditId'
      fullPath: '/sites/$id/audits/$auditId'
      preLoaderRoute: typeof AuthenticatedSitesIdAuditsAuditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedSettingsActivityRoute: typeof AuthenticatedSettingsActivityRoute
  AuthenticatedSettingsGeneralRoute: typeof AuthenticatedSettingsGeneralRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedSettingsTeamRoute: typeof AuthenticatedSettingsTeamRoute
  AuthenticatedSitesIdRoute: typeof AuthenticatedSitesIdRoute
  AuthenticatedProjectsIdAuditsRoute: typeof AuthenticatedProjectsIdAuditsRoute
  AuthenticatedProjectsIdExportsRoute: typeof AuthenticatedProjectsIdExportsRoute
  AuthenticatedProjectsIdIssuesRoute: typeof AuthenticatedProjectsIdIssuesRoute
  AuthenticatedProjectsIdSitesRoute: typeof AuthenticatedProjectsIdSitesRoute
  AuthenticatedSitesIdAuditsAuditIdRoute: typeof AuthenticatedSitesIdAuditsAuditIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedSettingsActivityRoute: AuthenticatedSettingsActivityRoute,
  AuthenticatedSettingsGeneralRoute: AuthenticatedSettingsGeneralRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
  AuthenticatedSettingsTeamRoute: AuthenticatedSettingsTeamRoute,
  AuthenticatedSitesIdRoute: AuthenticatedSitesIdRoute,
  AuthenticatedProjectsIdAuditsRoute: AuthenticatedProjectsIdAuditsRoute,
  AuthenticatedProjectsIdExportsRoute: AuthenticatedProjectsIdExportsRoute,
  AuthenticatedProjectsIdIssuesRoute: AuthenticatedProjectsIdIssuesRoute,
  AuthenticatedProjectsIdSitesRoute: AuthenticatedProjectsIdSitesRoute,
  AuthenticatedSitesIdAuditsAuditIdRoute:
    AuthenticatedSitesIdAuditsAuditIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  InviteTokenRoute: InviteTokenRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalSecurityRoute: LegalSecurityRoute,
  LegalTermsRoute: LegalTermsRoute,
  ResetPasswordTokenRoute: ResetPasswordTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
