name: Setup Node and pnpm
description: Install Node.js, pnpm, and workspace dependencies.

inputs:
  node-version:
    description: Node.js version to install.
    default: 26.0.0
  pnpm-version:
    description: pnpm version to install.
    default: 11.0.8
  install:
    description: Install workspace dependencies.
    default: 'true'

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v6
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup node
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Install dependencies
      if: inputs.install == 'true'
      shell: bash
      run: pnpm install --frozen-lockfile
